// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace AI1
{
    public partial class ChessModel1
    {
        /// <summary>
        /// model input class for ChessModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Kc")]
            public string Kc { get; set; }

            [ColumnName(@"Kr")]
            public float Kr { get; set; }

            [ColumnName(@"Rc")]
            public string Rc { get; set; }

            [ColumnName(@"Rr")]
            public float Rr { get; set; }

            [ColumnName(@"kc2")]
            public string Kc2 { get; set; }

            [ColumnName(@"kr2")]
            public float Kr2 { get; set; }

            [ColumnName(@"result")]
            public string Result { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ChessModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName("PredictedLabel")]
            public string Prediction { get; set; }

            public float[] Score { get; set; }
        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("ChessModel1.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
